### ISSUE TITLE
Can we make text in hero white?

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/cloud-init#28]

**Comment by barrymcgee** [comment]
![screenshot 2016-02-01 11 18 33](https://cloud.githubusercontent.com/assets/505570/12716022/94f1b480-c8d5-11e5-9985-41234805154b.png)

@yaili We'd need to darken or change the cloud background image?

**Comment by barrymcgee** [comment]
@yaili Have just noticed #26 - to make bg aubergine.
