### ISSUE TITLE
Empty footer

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/cloud-init#33]
Currently the footer section is empty. We should remove the footer section if there is no content.

**Comment by barrymcgee** [comment]
@anthonydillon I'm not sure what you mean - the footer has copyright and "report a bug" link?

https://github.com/ubuntudesign/cloud-init/blob/master/index.html#L259

**Comment by anthonydillon** [comment]
My mistake, I was just looking at the source. There is an empty footer at the bottom of the page:

```html
<footer class="site-footer">

</footer>
```

**Comment by anthonydillon** [comment]
view-source:http://barrymcgee.github.io/cloud-init/
