### ISSUE TITLE
Support section could be grey?

### ISSUE THREAD

**Issue by pmahnke** [ubuntudesign/cloud-init#6]
for Yaili, but could it look like the 'Four ways to get OpenStack' on Ubuntu section on ubuntu.com/cloud/openstack ?

also, full width?

**Comment by pmahnke** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;hOcAXORj&#x2F;28-review-demo"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Review demo</a>

**Comment by yaili** [comment]
Agreed. Should all the rows on the site be full width too?
