### ISSUE TITLE
Intro text

### ISSUE THREAD

**Issue by pmahnke** [ubuntudesign/cloud-init#7]
for frankie... I think we need to rethink the text at the top a bit  based on this design to feel more like MAAS.io

**Comment by pmahnke** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;UiMvteh2&#x2F;76-assigned-cloud-init-intro-text"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Assigned [cloud-init] Intro text</a>

**Comment by richmccartney** [comment]
Test

**Comment by pmahnke** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;hOcAXORj&#x2F;28-review-demo"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Review demo</a>
